project:
  type: website
  output-dir: docs

website:
  title: "rleripio.com"
  site-url: rleripio.com
  google-analytics: "G-4HE60YY1JD"
  search: false
  open-graph: true 
  page-footer:
    left: "[Source](http://github.com/leripio/rleripio.com)"
    right: "Built with {{< iconify simple-icons:quarto >}} [Quarto](http://quarto.org)"
  navbar:
    id: top-nav
    pinned: true
    toggle-position: right
    title: RLeripio.com
    #logo: images/logo.png
    site-url: https://www.rleripio.com
    right:
      - book/index.qmd
      - talks/index.qmd
      - text: "CV"
        href: files/Resume.pdf
        target: _blank
    tools:
    - icon: github
      text: GitHub
      href: https://github.com/leripio
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/leripiorenato/

format:
  html:
    theme: cosmo
    css: styles.css
